export const FOOD_ITEM_LIST_REQUEST = "FOOD_ITEM_LIST_REQUEST";
export const FOOD_ITEM_LIST_SUCCESS = "FOOD_ITEM_LIST_SUCCESS";
export const FOOD_ITEM_LIST_FAIL = "FOOD_ITEM_LIST_FAIL";

export const FOOD_ITEM_DETAILS_REQUEST = "FOOD_ITEM_DETAILS_REQUEST";
export const FOOD_ITEM_DETAILS_SUCCESS = "FOOD_ITEM_DETAILS_SUCCESS";
export const FOOD_ITEM_DETAILS_FAIL = "FOOD_ITEM_DETAILS_FAIL";

export const FOOD_ITEM_DELETE_REQUEST = "FOOD_ITEM_DELETE_REQUEST";
export const FOOD_ITEM_DELETE_SUCCESS = "FOOD_ITEM_DELETE_SUCCESS";
export const FOOD_ITEM_DELETE_FAIL = "FOOD_ITEM_DELETE_FAIL";

export const FOOD_ITEM_CREATE_REQUEST = "FOOD_ITEM_CREATE_REQUEST";
export const FOOD_ITEM_CREATE_SUCCESS = "FOOD_ITEM_CREATE_SUCCESS";
export const FOOD_ITEM_CREATE_FAIL = "FOOD_ITEM_CREATE_FAIL";
export const FOOD_ITEM_CREATE_RESET = "FOOD_ITEM_CREATE_RESET";

export const FOOD_ITEM_UPDATE_REQUEST = "FOOD_ITEM_UPDATE_REQUEST";
export const FOOD_ITEM_UPDATE_SUCCESS = "FOOD_ITEM_UPDATE_SUCCESS";
export const FOOD_ITEM_UPDATE_FAIL = "FOOD_ITEM_UPDATE_FAIL";
export const FOOD_ITEM_UPDATE_RESET = "FOOD_ITEM_UPDATE_RESET";

export const FOOD_ITEM_CREATE_REVIEW_REQUEST =
	"FOOD_ITEM_CREATE_REVIEW_REQUEST";
export const FOOD_ITEM_CREATE_REVIEW_SUCCESS =
	"FOOD_ITEM_CREATE_REVIEW_SUCCESS";
export const FOOD_ITEM_CREATE_REVIEW_FAIL = "FOOD_ITEM_CREATE_REVIEW_FAIL";
export const FOOD_ITEM_CREATE_REVIEW_RESET = "FOOD_ITEM_CREATE_REVIEW_RESET";

export const FOOD_ITEM_TOP_REQUEST = "FOOD_ITEM_TOP_REQUEST";
export const FOOD_ITEM_TOP_SUCCESS = "FOOD_ITEM_TOP_SUCCESS";
export const FOOD_ITEM_TOP_FAIL = "FOOD_ITEM_TOP_FAIL";
